### PR TITLE
Add Travis badge

### PR DESCRIPTION
**Pull request by ewjoachim**

### CODE REVIEW

**Comment by k4nar** [comment]
I'm pretty sure you'll have to do PR "fix Travis build" first ;) .

**Comment by ewjoachim** [comment]
I wanted to see if travis would pass actually. And not. I'd say merge this PR, because it will help us see that travis doesn't pass. Then either fix travis or leave this repo, but at least, we'll be explicit about travis not passing ^^

**Comment by ewjoachim** [comment]
@k4nar ?

**Comment by k4nar** [comment]
Ok why not.

**Pull request merged**
